-- Run this in your Supabase SQL Editor to create the table

create table public.transcripts (
  id bigint generated by default as identity primary key,
  session_id text not null,
  speaker text,
  text text,
  confidence float,
  turn_order int,
  timestamp timestamptz default now(),
  created_at timestamptz default now(),
  metadata jsonb  -- New column for rich analysis data (words, wpm, etc.)
);

-- Optional: Enable RLS if you want to restrict access
alter table public.transcripts enable row level security;

-- Allow anon insert (if using anon key) or service_role (always allowed)
create policy "Allow anonymous inserts" on public.transcripts for insert with check (true);
create policy "Allow anonymous select" on public.transcripts for select using (true);
