#!/usr/bin/env python3
"""
Generate beautiful HTML report from session analysis (Diarization-Enabled)
"""

import json
import sys
from pathlib import Path
from datetime import datetime


HTML_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Session Analysis Report</title>
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'SF Pro Display', sans-serif;
            background: linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%);
            padding: 40px 20px;
            color: #333;
        }}
        .container {{
            max-width: 1200px;
            margin: 0 auto;
            background: white;
            border-radius: 20px;
            box-shadow: 0 20px 60px rgba(0,0,0,0.1);
            overflow: hidden;
        }}
        .header {{
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 40px;
            text-align: center;
        }}
        .header h1 {{ font-size: 36px; margin-bottom: 10px; }}
        .header p {{ opacity: 0.9; font-size: 18px; }}
        .content {{ padding: 40px; }}
        .section {{
            margin-bottom: 40px;
            padding: 30px;
            background: #f8f9fa;
            border-radius: 15px;
            border-left: 5px solid #667eea;
        }}
        .section h2 {{
            color: #667eea;
            font-size: 24px;
            margin-bottom: 20px;
            display: flex;
            align-items: center;
            gap: 10px;
        }}

        /* --- NEW: Speaker Column Layout --- */
        .speaker-grid {{
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 30px;
        }}
        .speaker-column h3 {{
            font-size: 20px;
            color: #333;
            margin-bottom: 15px;
            padding-bottom: 10px;
            border-bottom: 2px solid #eee;
        }}
        .student-column h3 {{ color: #0c5460; }}
        .teacher-column h3 {{ color: #764ba2; }}
        /* --- END NEW --- */

        .metric {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
            gap: 20px;
            margin: 20px 0;
        }}
        .metric-card {{
            background: white;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.05);
        }}
        .metric-card h3 {{
            color: #666;
            font-size: 14px;
            text-transform: uppercase;
            margin-bottom: 10px;
            border-bottom: none; /* Override column h3 */
        }}
        .metric-card .value {{
            font-size: 32px;
            font-weight: bold;
            color: #667eea;
        }}
        .metric-card .label {{
            color: #999;
            font-size: 14px;
            margin-top: 5px;
        }}
        .list-item {{
            background: white;
            padding: 15px;
            margin: 10px 0;
            border-radius: 8px;
            border-left: 3px solid #667eea;
        }}
        .badge {{
            display: inline-block;
            padding: 5px 15px;
            border-radius: 20px;
            font-size: 12px;
            font-weight: 600;
            margin-right: 10px;
        }}
        .badge-success {{ background: #d4edda; color: #155724; }}
        .badge-warning {{ background: #fff3cd; color: #856404; }}
        .badge-danger {{ background: #f8d7da; color: #721c24; }}
        .badge-info {{ background: #d1ecf1; color: #0c5460; }}
        .footer {{
            text-align: center;
            padding: 30px;
            color: #999;
            border-top: 1px solid #eee;
        }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>📊 Session Analysis</h1>
            <p>{student_name} with {teacher_name}</p>
            <p style="opacity: 0.7; font-size: 14px;">{date}</p>
        </div>

        <div class="content">
            {sections}
        </div>

        <div class="footer">
            <p>Generated by Semantic Surfer • {timestamp}</p>
        </div>
    </div>
</body>
</html>
"""

def generate_metric_card(title, value, label=""):
    """Helper to create a metric card"""
    return f"""
    <div class="metric-card">
        <h3>{title}</h3>
        <div class="value">{value}</div>
        <div class="label">{label}</div>
    </div>
    """

def generate_speaker_column(speaker_name: str, analysis: dict) -> str:
    """Generate an HTML column for a single speaker's analysis"""

    col_html = []

    # --- Speaking Rate ---
    if 'speaking_rate' in analysis and 'error' not in analysis['speaking_rate']:
        sr = analysis['speaking_rate']
        col_html.append("<h4>🗣️ Speaking Rate</h4>")
        col_html.append('<div class="metric">')
        col_html.append(generate_metric_card("Average WPM", sr['average_wpm'], sr['native_comparison']))
        col_html.append(generate_metric_card("WPM Range", f"{sr['min_wpm']} - {sr['max_wpm']}", "Min - Max"))
        col_html.append('</div>')

    # --- Pauses ---
    if 'pauses' in analysis and 'message' not in analysis['pauses']:
        p = analysis['pauses']
        col_html.append("<h4>⏸️ Pause Analysis</h4>")
        col_html.append('<div class="metric">')
        col_html.append(generate_metric_card("Total Pauses", p['total_pauses']))
        col_html.append(generate_metric_card("Long Pauses", p['long_pauses'], "&gt;1 second"))
        col_html.append(generate_metric_card("Fluency Score", p['fluency_score'], "", style="font-size: 18px;"))
        col_html.append('</div>')

    # --- Complexity ---
    if 'complexity' in analysis and 'error' not in analysis['complexity']:
        c = analysis['complexity']
        col_html.append("<h4>📚 Vocabulary Complexity</h4>")
        col_html.append('<div class="metric">')
        col_html.append(generate_metric_card("Total Words", c['total_words']))
        col_html.append(generate_metric_card("Unique Words", c['unique_words'], f"{int(c['vocabulary_diversity']*100)}% diversity"))
        col_html.append(generate_metric_card("Level", c['complexity_level'], "", style="font-size: 18px;"))
        col_html.append('</div>')

    # --- Fillers ---
    if 'fillers' in analysis:
        f = analysis['fillers']
        col_html.append("<h4>💬 Filler Words</h4>")
        col_html.append('<div class="metric">')
        col_html.append(generate_metric_card("Total Fillers", f['total_fillers'], f"{f['filler_percentage']}% of speech"))
        col_html.append(generate_metric_card("Impact", f['fluency_impact'], "", style="font-size: 18px;"))
        col_html.append('</div>')
        top_fillers = ''.join([f'<span class="badge badge-warning">{k}: {v}</span>' for k, v in f.get('by_type', {}).items()])
        col_html.append(f'<div style="margin-top: 10px;">{top_fillers}</div>')

    return '\n'.join(col_html)


def generate_html_report(analysis: dict) -> str:
    """Generate beautiful HTML report from analysis"""

    info = analysis['session_info']
    teacher_name = info.get('teacher_name', 'Teacher')
    student_name = info.get('student_name', 'Student')

    sections = []

    # --- NEW: Per-Speaker Analysis Section ---
    sections.append('<div class="section">')
    sections.append("<h2>📊 Per-Speaker Analysis</h2>")
    sections.append('<div class="speaker-grid">')

    # Student Column
    student_analysis = analysis.get('analysis_by_speaker', {}).get(student_name)
    if student_analysis:
        sections.append('<div class="speaker-column student-column">')
        sections.append(f"<h3>{student_name} (Student)</h3>")
        sections.append(generate_speaker_column(student_name, student_analysis))
        sections.append('</div>')
    else:
        sections.append(f"<div>Error: Analysis for '{student_name}' not found.</div>")

    # Teacher Column
    teacher_analysis = analysis.get('analysis_by_speaker', {}).get(teacher_name)
    if teacher_analysis:
        sections.append('<div class="speaker-column teacher-column">')
        sections.append(f"<h3>{teacher_name} (Teacher)</h3>")
        sections.append(generate_speaker_column(teacher_name, teacher_analysis))
        sections.append('</div>')
    else:
        sections.append(f"<div>Error: Analysis for '{teacher_name}' not found.</div>")

    sections.append('</div>') # End speaker-grid
    sections.append('</div>') # End section
    # --- END NEW ---


    # --- Session-Wide Analysis Sections ---

    # Passion Moments Section
    if 'passion_moments' in analysis and 'message' not in analysis['passion_moments']:
        pm = analysis['passion_moments']
        sections.append(f"""
        <div class="section">
            <h2>🔥 Passion & Engagement (Session-Wide)</h2>
            <div class="metric">
                <div class="metric-card">
                    <h3>Baseline WPM</h3>
                    <div class="value">{pm['baseline_wpm']}</div>
                </div>
                <div class="metric-card">
                    <h3>Passion Moments</h3>
                    <div class="value">{pm['passion_moments_count']}</div>
                    <div class="label">&gt;{pm['passion_threshold']} WPM</div>
                </div>
            </div>
            <p style="margin: 20px 0; padding: 15px; background: white; border-radius: 8px;">
                <strong>Insight:</strong> {pm['insight']}
            </p>
            <h3>High Engagement Moments</h3>
            {''.join([f'<div class="list-item"><span class="badge badge-success">{m["speaker"]} @ {m["wpm"]} WPM</span>{m["transcript"][:100]}...</div>' for m in pm.get('passion_moments', [])[:5]])}
        </div>
        """)

    # Grammar Patterns Section
    if 'grammar_patterns' in analysis and analysis['grammar_patterns']['patterns_found'] > 0:
        gp = analysis['grammar_patterns']
        sections.append(f"""
        <div class="section">
            <h2>✏️ Grammar Patterns (Session-Wide)</h2>
            <div class="metric">
                <div class="metric-card">
                    <h3>Patterns Found</h3>
                    <div class="value">{gp['patterns_found']}</div>
                </div>
            </div>
            <p style="margin: 10px 0; color: #666; font-size: 14px;">{gp['note']}</p>
            {''.join([f'<h3 style="margin-top: 20px;">{k.replace("_", " ").title()}: {v}</h3>' + ''.join([f'<div class="list-item"><span class="badge badge-danger">{p["speaker"]} (Turn {p["turn_order"]})</span>{p["pattern"]} - {p["transcript"]}</div>' for p in gp['details'][k][:3]]) for k, v in gp['by_type'].items() if v > 0])}
        </div>
        """)

    # Marked Turns Section
    if 'marked_turns' in analysis and analysis['marked_turns']['total_marked'] > 0:
        mt = analysis['marked_turns']
        sections.append(f"""
        <div class="section">
            <h2>⭐ Marked Turns</h2>
            <div class="metric">
                <div class="metric-card">
                    <h3>Total Marked</h3>
                    <div class="value">{mt['total_marked']}</div>
                </div>
                {''.join([f'<div class="metric-card"><h3>{k}</h3><div class="value">{v}</div></div>' for k, v in mt['by_type'].items()])}
            </div>
            {''.join([f'<div class="list-item"><span class="badge badge-info">{t["speaker"]} ({t["mark_type"]})</span>{t["transcript"]}</div>' for t in mt['marked_turns'][:10]])}
        </div>
        """)

    # --- NEW: Action Items Section ---
    if 'action_items' in analysis and analysis['action_items']['total_action_items'] > 0:
        ai = analysis['action_items']
        sections.append(f"""
        <div class="section">
            <h2>🚨 Action Items</h2>
            <div class="metric">
                <div class="metric-card">
                    <h3>Total Detected</h3>
                    <div class="value">{ai['total_action_items']}</div>
                </div>
            </div>
            {''.join([f'<div class="list-item"><span class="badge badge-danger">{item["speaker"]} (Turn {item["turn_order"]})</span>{item["transcript"]}</div>' for item in ai.get('action_items', [])])}
        </div>
        """)
    # --- END NEW ---

    # Generate final HTML
    html = HTML_TEMPLATE.format(
        teacher_name=teacher_name,
        student_name=student_name,
        date=info.get('start_time', 'Unknown')[:10],
        timestamp=datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
        sections=''.join(sections)
    )

    return html


def main():
    if len(sys.argv) < 2:
        print("Usage: python generate_report.py <_analysis.json>")
        sys.exit(1)

    analysis_file = Path(sys.argv[1])

    if not analysis_file.exists():
        print(f"Error: Analysis file not found: {analysis_file}")
        sys.exit(1)

    with open(analysis_file, 'r') as f:
        analysis = json.load(f)

    html = generate_html_report(analysis)

    # --- FILENAME FIX ---
    # Creates report from the analysis file name
    # e.g., session_..._Student-X_analysis.json -> session_..._Student-X_analysis_report.html
    output_file = analysis_file.parent / f"{analysis_file.stem}_report.html"
    # --- END FIX ---

    with open(output_file, 'w') as f:
        f.write(html)

    print(f"✅ Report generated: {output_file}")
    print(f"   Open it in your browser to view!")


if __name__ == '__main__':
    main()
