#!/bin/bash

# Configuration
API_URL="https://gitenglish.com/api/mcp" # Change to localhost:3000 if running Hub locally
MCP_SECRET="${MCP_SECRET:-your_secret_here}"

echo "🚀 Launching Test Payload to The Castle ($API_URL)..."

# Sample Payload matching the High-Definition Schema
curl -X POST "$API_URL" \
  -H "Authorization: Bearer $MCP_SECRET" \
  -H "Content-Type: application/json" \
  -d '{
    "action": "ingest.createSession",
    "studentId": "Test Student",
    "params": {
        "studentName": "Test Student",
        "sessionDate": "'"$(date -u +"%Y-%m-%dT%H:%M:%SZ")"'",
        "duration": 10.5,
        "transcriptText": "Speaker A: Hello.\\nSpeaker B: Hi there.",
        "punctuatedTranscript": "Speaker A: Hello. Speaker B: Hi there.",
        "sentences": [
            {"text": "Hello.", "start": 0, "end": 1000},
            {"text": "Hi there.", "start": 1000, "end": 2000}
        ],
        "turns": [
            {
                "speaker": "A",
                "transcript": "Hello",
                "words": [
                    {"text": "Hello", "start": 0, "end": 1000, "confidence": 0.99, "speaker": "A"}
                ]
            },
            {
                "speaker": "B",
                "transcript": "Hi there",
                "words": [
                    {"text": "Hi", "start": 1000, "end": 1500, "confidence": 0.98, "speaker": "B"},
                    {"text": "there", "start": 1500, "end": 2000, "confidence": 0.98, "speaker": "B"}
                ]
            }
        ],
        "lmAnalysis": "Test analysis response.",
        "errorPhenomena": [
            {
                "item": "Hi there",
                "correction": "Hello there",
                "category": "Register",
                "explanation": "Informal greeting.",
                "source": "RULE_BASED"
            }
        ],
        "notes": "Test payload generated by scripts/test_hub_connection.sh"
    }
}'

echo -e "\n\n✅ Request Sent. Check the Hub logs for the result!"
